#!/bin/sh -efu

. dconf-locker-functions

# Check the script is being run by root
if [[ "$(id -u)" != "0" ]]; then
   echo "This script must be run as root!"
   exit 1
fi

case $1 in
     -la|--lockall)
          lock "all"
          ;;
     -ll|--locklist)
          lock "list"
          ;;
     -u|--unlock)
          unlock
          ;;
     *)
          echo -e \
"Usage: command argument
Arguments:
        -la (--lockall) - to lock all dconf configurations
        -ll (--locklist) - to lock a list of dconf configurations
                        example: command -ll schema1 schema2 (without path and .gschema.xml)
        -u (--unlock) - to unlock all dconf configurations"
          ;;
esac
