#!/bin/sh -efu

argc=$#
argv=("$@")
# usage: ${argv[0]}

. dconf-locker-functions

printHelpMessage()
{
    echo -e \
"Usage: command argument
Arguments:
        -la (--lockall) - to lock all dconf configurations
        -ll (--locklist) - to lock a list of dconf configurations
                        example: command -ll schema1 schema2 (without path and .gschema.xml)
        -ua (--unlockall) - to unlock all dconf configurations
        -ul (--unlocklist) - to unlock list of dconf configurations
                        example: command -ll schema1 schema2 (without path and .gschema.xml)"
}

# Check the script is being run by root
if [[ "$(id -u)" != "0" ]]; then
   echo "This script must be run as root!"
   exit 1
fi

case $1 in
    -la|--lockall)
        if [[ $argc == 1 ]]; then
            lock "all"
        else
            printHelpMessage
        fi
        ;;
    -ll|--locklist)
        if [[ $argc > 1 ]]; then
            lock "list" $argc ${argv[*]}
        else
            printHelpMessage
        fi
        ;;
    -ua|--unlockall)
        if [[ $argc == 1 ]]; then
            unlock "all"
        else
            printHelpMessage
        fi
        ;;
    -ul|--unlocklist)
        if [[ $argc > 1 ]]; then
            unlock "list" $argc ${argv[*]}
        else
            printHelpMessage
        fi
        ;;
    *) printHelpMessage
        ;;
esac
